name: care_nest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  connectivity_plus: ^6.0.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/